export enum DeliveryStatus {
  CREATED = 'CREATED',
  APPROVED = 'APPROVED',
  PACKED = 'PACKED',
  DISPATCHED = 'DISPATCHED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERY_EXCEPTION = 'DELIVERY_EXCEPTION',
  DELIVERED = 'DELIVERED'
}
