export enum DeliveryExceptionReason {
  SHOP_CLOSED = 'SHOP_CLOSED',
  CUSTOMER_UNAVAILABLE = 'CUSTOMER_UNAVAILABLE',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  VEHICLE_BREAKDOWN = 'VEHICLE_BREAKDOWN'
}
