export enum DeliveryExceptionType {
  SHOP_CLOSED = 'SHOP_CLOSED',
  CUSTOMER_UNREACHABLE = 'CUSTOMER_UNREACHABLE',
  PARTIAL_DELIVERY = 'PARTIAL_DELIVERY',
  DAMAGED_ITEMS = 'DAMAGED_ITEMS',
  VEHICLE_BREAKDOWN = 'VEHICLE_BREAKDOWN',
  OTHER = 'OTHER'
}
