import { DeliveryExceptionReason } from './delivery-exception-reason.enum';

export interface DeliveryException {

  /** generated by backend */
  exceptionId?: string;   // ✅ OPTIONAL

  orderId: string;
  driverId: string;

  reason: DeliveryExceptionReason;

  notes?: string;

  reportedAt: string;

  resolved?: boolean;
}
